In [1]:
!pip install torch torchvision torchaudio

In [2]:
import torch
import torch.nn as nn

print(torch.__version__)

ModuleNotFoundError: No module named 'torch'

In [4]:
import sys

print(sys.executable)

e:\DSA-ML-30DAYS\ML_30_DAYS\.venv\Scripts\python.exe


In [5]:
python -m pip install torch torchvision torchaudio

SyntaxError: invalid syntax (1867111728.py, line 1)

In [6]:
import sys

!{sys.executable} -m pip install torch torchvision torchaudio

  Using cached torch-2.13.0-cp312-cp312-win_amd64.whl.metadata (39 kB)
  Using cached torchvision-0.28.0-cp312-cp312-win_amd64.whl.metadata (5.6 kB)
  Using cached filelock-3.29.7-py3-none-any.whl.metadata (2.0 kB)
  Using cached fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Using cached torch-2.13.0-cp312-cp312-win_amd64.whl (122.1 MB)
Using cached torchvision-0.28.0-cp312-cp312-win_amd64.whl (4.1 MB)
Using cached fsspec-2026.6.0-py3-none-any.whl (203 kB)
Using cached filelock-3.29.7-py3-none-any.whl (46 kB)



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
import torch
import torch.nn as nn

print("PyTorch Version:", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())

PyTorch Version: 2.13.0+cpu
CUDA Available: False


In [8]:
import torch

x = torch.tensor([[1,2],[3,4]])

print(x)
print(x.shape)
print(x.dtype)
print(x.device)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
torch.int64
cpu


In [9]:
import torch
import torch.nn as nn

layer = nn.Linear(4,3)

x = torch.randn(1,4)

print("Input:")
print(x)

print("\nOutput:")
print(layer(x))

Input:
tensor([[ 0.1658,  0.2236,  0.3644, -0.8229]])

Output:
tensor([[-0.0907,  0.8947,  0.7049]], grad_fn=<AddmmBackward0>)


In [10]:
x = torch.randn(1,4)

In [11]:
layer = nn.Linear(4,3)

In [12]:
nn.Linear(4,3)

Linear(in_features=4, out_features=3, bias=True)

In [13]:
import torch
import torch.nn as nn

In [14]:
layer = nn.Linear(4, 3)

print(layer)

Linear(in_features=4, out_features=3, bias=True)


In [15]:
x = torch.randn(1, 4)

print("Input:")
print(x)

output = layer(x)

print("\nOutput:")
print(output)

Input:
tensor([[-0.2124,  2.6636, -0.5129, -0.2034]])

Output:
tensor([[ 0.4113, -0.8195,  0.8870]], grad_fn=<AddmmBackward0>)


In [16]:
relu = nn.ReLU()

x = torch.tensor([[-2.0, -1.0, 0.0, 2.0, 5.0]])

print("Before ReLU")
print(x)

print("\nAfter ReLU")
print(relu(x))

Before ReLU
tensor([[-2., -1.,  0.,  2.,  5.]])

After ReLU
tensor([[0., 0., 0., 2., 5.]])


In [17]:
class NeuralNetwork(nn.Module):

    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(4, 8)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(8, 2)

    def forward(self, x):

        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)

        return x

In [18]:
model = NeuralNetwork()

print(model)

NeuralNetwork(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=2, bias=True)
)


In [19]:
sample = torch.randn(1, 4)

print(sample)

tensor([[-0.1223,  0.1966, -0.4135, -1.6177]])


In [20]:
prediction = model(sample)

print("Prediction:")
print(prediction)

Prediction:
tensor([[ 0.4386, -0.3494]], grad_fn=<AddmmBackward0>)


In [21]:
batch = torch.randn(5, 4)

print(batch)

tensor([[-0.6203,  1.5001, -0.3876, -2.0662],
        [-2.3054,  0.2266,  0.4824, -0.3269],
        [ 0.6443, -0.1856,  0.3705, -0.6872],
        [-0.1520,  0.7762,  0.8470,  0.0201],
        [ 0.7971, -0.6802,  0.9908, -1.0331]])


In [22]:
predictions = model(batch)

print(predictions)

tensor([[ 0.5403, -0.3089],
        [ 0.3331, -0.0902],
        [ 0.0338, -0.3701],
        [-0.0295, -0.3412],
        [ 0.0312, -0.3683]], grad_fn=<AddmmBackward0>)


In [23]:
for name, param in model.named_parameters():
    print(name)
    print(param.shape)
    print(param)
    print("-" * 50)
    

fc1.weight
torch.Size([8, 4])
Parameter containing:
tensor([[-0.2278, -0.0173, -0.4435, -0.3024],
        [ 0.3183,  0.1262, -0.4544,  0.3420],
        [-0.0821, -0.3691, -0.3232, -0.1986],
        [ 0.2985,  0.4867,  0.2058, -0.3489],
        [-0.5000, -0.2508, -0.0598,  0.4965],
        [ 0.0033,  0.0603,  0.2309,  0.0923],
        [-0.2752, -0.0732, -0.0586,  0.4046],
        [-0.3211,  0.2402, -0.2558, -0.2155]], requires_grad=True)
--------------------------------------------------
fc1.bias
torch.Size([8])
Parameter containing:
tensor([-0.0083,  0.0219,  0.0433, -0.4281,  0.3496,  0.4784,  0.0387, -0.0482],
       requires_grad=True)
--------------------------------------------------
fc2.weight
torch.Size([2, 8])
Parameter containing:
tensor([[ 0.2553, -0.3428,  0.1727, -0.1297, -0.1619, -0.0438,  0.3374,  0.3456],
        [-0.2730, -0.3354,  0.1908,  0.0835,  0.3304, -0.1104, -0.3229,  0.2102]],
       requires_grad=True)
--------------------------------------------------
fc2.bia